# version: '2.1'

# services:
#   nebula.webapp-angular:
#     image: nebula.webapp-angular
#     build: .
#     environment:
#       NODE_ENV: production
#     ports:
#       - 3000:3000

# Ref:
# https://docs.docker.com/compose/overview/  
# https://docs.docker.com/compose/compose-file/
version: '3'

services:
  webapp:
    image: nebula.webapp-angular
    build: .
    ports: 
      - "4200:80"

