# Ref:
# https://docs.docker.com/compose/overview/  
# https://docs.docker.com/compose/compose-file/
version: '3'

services:
  webapp:
    image: nebula.webapp-angular
    ports: 
      - "4200:80"
    networks:
      - webnet
networks:
  webnet:


# docker swarm init
# docker stack deploy -c docker-compose.yml nebula

# Take the app down 
# docker stack rm nebula

# Take down the swarm.
# docker swarm leave --force

# docker service ls

# docker container ls -a
